//^ readme
const String readme = "These files are autogenerated by programs made by Sem Van Broekhoven using google drive as file storage. Please don't edit these files to not mess up data.";
// TODO add more to contentser

//^ data
const String data = '{"ideas": {}, "projects": {}, "archive": {}}';

//^ settings
const String settings = '{"darkmode": false, "colorscheme": "orange"}';