//^ readme
const String readme = "These files are autogenerated by programs made by Sem Van Broekhoven using google drive as file storage. Please don't edit these files to not mess up data.";
// TODO add more to contentser

//^ projects data
const String projectsData = '{"ideas": [], "projects": [], "archive": []}';

//^ settings
const String settings = '{"darkmode": false, "colorscheme": "orange", "showProjectSize": true, "funnyProjectSize": false}';

//^ category
const String categoryData = '["app", "finish", "zolder"]';
