name: keeper_of_projects
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  googleapis: ^10.0.0
  google_sign_in: ^5.0.7
  http: ^0.13.3
  collection: ^1.17.2
  firebase_core: ^3.1.0
  path_provider: 2.1.3
  deepcopy: ^1.1.2
  percent_indicator: ^4.0.1
  flutter_staggered_grid_view:
  uuid: ^4.4.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
