name: keeper_of_projects
description: "PLNM! A userfriendly cross-platform planning app with tons of features."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  googleapis: ^10.0.0
  google_sign_in: ^5.0.7
  http: ^0.13.3
  collection: ^1.17.2
  firebase_core: ^3.1.0
  path_provider: 2.1.4
  deepcopy: ^1.1.2
  percent_indicator: ^4.0.1
  flutter_staggered_grid_view:
  uuid: ^4.4.2
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  url_launcher: ^6.3.0
  oauth2: ^2.0.2
  window_to_front: ^0.0.3
  flutter_secure_storage: ^8.0.0
  universal_platform: ^1.0.0+1
  window_manager: ^0.4.2
  intl: ^0.18.0 




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
